# File build-test-publish-dotnetcore.yml

parameters:
  name: ''
  project: ''
  testProject: ''
  buildConfiguration: ''
  artifactName: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 2.0.3'
    inputs:
      version: 2.0.3

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '${{ parameters.project }}'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '${{ parameters.project }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '${{ parameters.testProject }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '${{ parameters.project }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: ${{ parameters.artifactName }}